[tool.poetry]
name = "easy-git-cli"
version = "0.2.0"
description = "A CLI tool to simplify Git workflows"
authors = ["Omar Allouch <allouchomar1@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
gitpython = "^3.1.43"
questionary = "^2.0.1"

[tool.poetry.scripts]
easy-git = "src.main:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
