[tool.poetry]
name = "overture_maps_geoparquet_package"
version = "0.1.2"
description = "A Python package for downloading and processing Overture Maps geospatial data with configurable bounding box extraction and data management."
authors = ["ediakatos <ediakatos@mapaction.org>"]
license = "GPL-3.0-only"
readme = "README.md"
# the src directory
packages = [
    { include = "overture_maps_geoparquet_package", from = "src" }
]


[tool.poetry.dependencies]
python = "^3.10"
aiobotocore = "2.15.1"
aiohappyeyeballs = "2.4.3"
aiohttp = "3.10.9"
aioitertools = "0.12.0"
aiosignal = "1.3.1"
async-timeout = "4.0.3"
attrs = "24.2.0"
botocore = "1.35.23"
certifi = "2024.8.30"
click = "8.1.7"
frozenlist = "1.4.1"
fsspec = "2024.9.0"
geopandas = "1.0.1"
idna = "3.10"
jmespath = "1.0.1"
multidict = "6.1.0"
numpy = "2.1.2"
overturemaps = "0.9.0"
packaging = "24.1"
pandas = "2.2.3"
propcache = "0.2.0"
pyarrow = "17.0.0"
pyogrio = "0.10.0"
pyproj = "3.7.0"
python-dateutil = "2.9.0.post0"
pytz = "2024.2"
s3fs = "2024.9.0"
shapely = "2.0.6"
six = "1.16.0"
typing-extensions = "4.12.2"
tzdata = "2024.2"
urllib3 = "2.2.3"
wrapt = "1.16.0"
yarl = "1.14.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8.0"
pymarkdownlnt = "^0.9.23"
pytest = "^8.3.3"
ruff = "^0.6.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]

[tool.ruff]
fix = true
target-version = "py310"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D104"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*" = ["D", "S101", "ANN201", "PLR2004"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.poetry.scripts]
overture-downloader = "src.downloader:download_overture_data"
