[build-system]
requires = ["setuptools>=61.0", "Pandas>=2.2.2", "zipp>=3.17.0", "dicom2nifti>=2.4.11", "pydicom>=3.0.0", "regex>=2023.10.3"]
build-backend = "setuptools.build_meta"

[project]
name = "UnPAC"
version = "3.0.1"
authors = [
  { name="Ryan O'Keeffe", email="okeeffr1@tcd.ie" },
]
description = "A package that allows for the streamlining of retrieveing data from the UK-Biobank."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/RyanokTCD/UKB-UnPAC/tree/main"
Issues = "https://github.com/RyanokTCD/UKB-UnPAC/issues"