[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"

[project]
name = "kleinkram"
version = "0.36.3-dev20241113165309"
description = "A CLI for the ETH project kleinkram"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
  "typer",
  "httpx",
  "tqdm",
  "requests",
  "boto3",
  "botocore",
  "setuptools"
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

  [[project.authors]]
  name = "Johann Schwabe"
  email = "jschwab@ethz.ch"

  [project.urls]
  Homepage = "https://github.com/leggedrobotics/kleinkram"
  Issues = "https://github.com/leggedrobotics/kleinkram/issues"

  [project.scripts]
  klein = "kleinkram.main:app"
