[tool.poetry]
name = "profiling-tools"
version = "0.0.10"
description = "Python profiling tools using cProfile and pstats"
authors = ["Gustav Rasmussen"]
readme = "README.md"
packages = [{include = "profiling_tools"}]

[tool.poetry.dependencies]
python = "^3.11"
matplotlib = "^3.9.2"
pandas = "^2.2.3"
pytest = "^8.3.3"
pytest-cov = "^6.0.0"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
ruff = "^0.7.2"
mypy = "^1.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
