[tool.poetry]
name = "agritechtz-pycli"
version = "1.0.4"
description = ""
authors = ["Moses Kabungo <mose.kabungo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
pandas = "^2.2.3"
tqdm = "^4.67.0"
twine = "^5.1.1"
wheel = "^0.45.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
