[tool.poetry]
name = "t1cicd"
version = "0.1.0.1"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
click= "^8.1.7"
requests= "^2.32.3"
PyYAML="^6.0.2"
flasgger="^0.9.7.1"
Flask="^3.0.3"
pydantic="^2.9.2"
docker = "^7.1.0"
GitPython = "^3.1.41"
psycopg = "^3.2.3"
psycopg_pool = "^3.2.3"
rich="^13.9.4"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
coverage = "^7.6.1"
flake8 = "^7.1.1"
pylint = "^3.3.1"
pdoc = "^14.7.0"
pytest-mock="^3.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
cicd = "t1cicd.cicd.cli.cli:main"
server = "t1cicd.cicd.server.api:main"
example = "t1cicd.cicd.db.example:main"
