[tool.poetry]
name = "torchsystem"
version = "0.1.0"
description = "An IA training system, based on domain driven design and an event driven architecture, created on top of the pybondi library."
authors = ["Eric Cardozo <eric.m.cardozo@mi.unc.edu.ar>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mlregistry = "^1.0.0"
pybondi = "^0.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
