[package]
name = "jocv"
version = "0.1.11"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "jocv"
crate-type = ["cdylib"]

[dependencies]
ahash = "0.8.11"
cgmath = "0.18.0"
num-traits = "0.2.18"
pyo3 = "0.20.0"
