[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "py_brainrot"
version = "0.1.0"
authors = [
    {name = "WhiteMCWizard", email = "jweiss@whitemcwizard.nl"}
]
description = "The module that lets Gen Z grind Sigma code with max rizz"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["gen-z", "slang", "built-ins", "wrapper"]
dependencies = []
requires-python = ">=3.7"

[project.urls]
"Homepage" = "https://github.com/WhiteMCWizard/py_brainrot"
"Bug Tracker" = "https://github.com/WhiteMCWizard/py_brainrot/issues"