[project]
name = "InsarViz"
description = "Python package for analysis of (InSar) data cubes"
dynamic = []
authors = [
    { name = "Colin Thomas", email = "colin.thomas1@univ-grenoble-alpes.fr" },
    { name = "Margaux MouchenÃ©", email = "margaux.mouchene@univ-grenoble-alpes.fr" },
    { name = "Renaud Blanch", email = "renaud.blanch@univ-grenoble-alpes.fr" },
    { name = "Erwan Pathier", email = "erwan.pathier@univ-grenoble-alpes.fr" },
    { name = "Franck Thollard", email = "franck.thollard@univ-grenoble-alpes.fr" },
]
dependencies = [
    "PyOpenGL>=3.1.6",
    "PyQt5>=5.15.10",
    "pyqtgraph==0.13.7",
    "rasterio>=1.3.10",
    "owslib>=0.31",
]
requires-python = ">=3.9"
readme = "README.rst"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Visualization",
]
version = "2.2.1"

[project.license]
text = "GPLv3"

[project.urls]
Homepage = "https://gricad-gitlab.univ-grenoble-alpes.fr/deformvis/insarviz"

[project.scripts]
ts_viz = "insarviz.ts_viz:main"

[tool.setuptools.packages.find]
where = [
    ".",
]

[tool.setuptools.package-data]
icons = [
    "*.png",
    "alt/*.png",
]
insarviz = [
    "icons/*.png",
]

[tool.pdm]
distribution = true

[tool.pdm.version]
source = "file"
path = "insarviz/version.py"

[tool.pdm.dev-dependencies]
dev = [
    "mypy>=1.10.1",
    "pytest>=8.3",
]

[tool.mypy]
exclude = [
    "build/",
]

[[tool.mypy.overrides]]
module = [
    "OpenGL.*",
    "rasterio.*",
    "pyqtgraph.*",
]
ignore_missing_imports = true

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
