[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
PyGraphLib = ["py.typed"]

[project]
name = "PyGraphLib"
description = "A simple and incomplete graph library for Python"
version = "0.0.7"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "matplotlib",
]

[project.urls]
"Homepage" = "https://github.com/HansLuft778/PyGraphLib"