[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tkz"
version = "1.0.12"
description = "TikZ Figure Generator"
readme = "README.md"
authors = [
    {name = "David Woodburn", email = "david.woodburn@icloud.com"},
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.6"
dependencies = [
    "numpy",
]

[project.urls]
Homepage = "https://gitlab.com/davidwoodburn/tkz"
"Bug Tracker" = "https://gitlab.com/davidwoodburn/tkz/-/issues"

[tool.setuptools]
package-dir = {"" = "src"}
