[tool.poetry]
name = "arcane-mct"
version = "2.0.2"
description = "Package description"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
arcane-core = "^1"
arcane-datastore = "^1"
arcane-requests = "^0"
arcane-credentials = "^0.1"
google-api-python-client = ">=2.149.0"
backoff = "^1.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
