[project]
name = "mimedb"
version = "0.1.2"
description = "Sqlite db to store any content with mime type."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "mimedb"

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]
