[project]
name = "DockEva"
version = "1.2"
authors = [
  { name="Jun Hu", email="junh_cs@126.com" },
]
description = "Calculating the Docking RMSD between two ligands"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/jun-csbio/DockEva"
Issues = "https://github.com/jun-csbio/DockEva/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
DockEva = "DockEva.main:main"