[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chameleon_flask"
version = "0.0.3"
description = "Adds integration of the Chameleon template language to Flask and Quart."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Michael Kennedy", email = "michael@talkpython.fm" }
]
keywords = ["Flask", "Chameleon", "template", "integration"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]
dependencies = [
    "flask[async]",
    "Chameleon"
]

[project.urls]
"Homepage" = "https://github.com/mikeckennedy/chameleon-flask"

[tool.setuptools]
packages = ["chameleon_flask"]
