[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "agenteasy"
version = "0.2.2"
authors = [{ name = "Martin Lee", email = "lyzmooc@163.com" }]
description = "An AI library for humans"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = ["openai", "pydantic", "pydantic-settings", "Jinja2", "tiktoken"]
[project.optional-dependencies]
full = ["redis[hiredis]"]

[project.urls]
Homepage = "https://github.com/derMartinLi/agenteasy"
Issues = "https://github.com/derMartinLi/agenteasy/issues"
