[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "greenhub"
version = "1.0.7"
authors = [
    { email = "info@greenhub.ai" },
    { name = "Malte von Bloh" },
    { name = "Maximilian Zachow" },
    { name = "Linus Sander" },
    { name = "Jonas Engesser" },
    { name = "Florian Schmidt" },
    { name = "Christoph Starnecker" },
]
description = "Python toolbox for the greenhub.ai platform, offering capabilities for data access, model creation, and deployment."
readme = "README_PIP.md"
license = { file="LICENSE" }
requires-python = ">=3.1"
dependencies = [
    "pandas>=2.0.1",
    "requests>=2.20.1",
    "tqdm>=4.20.1",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://greenhub.ai"
Wiki = "https://docs.greenhub.ai"

[project.scripts]
greenhub = "greenhub.scripts:greenhub_cli_script"
