[tool.poetry]
name = "fbscribelogger"
version = "0.1.7.rc2"
description = ""
authors = ["Edward Z. Yang <ezyang@meta.com>"]
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.8.1"
thriftpy2 = "^0.5.2"
aiohttp = "^3.10.4"
typing-extensions = "^4.12.2"

[tool.poetry.dev-dependencies]
black = "^24.3.0"
flake8 = "^7"
mypy = "^1"
pytest = "^7"
usort = "^1"
ufmt = "^2"
lintrunner = "^0.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
