[build-system]
requires      = ["setuptools>=75.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asesurfacefinder"
version = "1.0.0"
description = "Machine learned location of chemical adsorbates on high-symmetry surface sites."
readme = "README.md"
authors = [{ name = "Joe Gilkes", email = "joe@joegilk.es" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Science/Research",
    "Operating System :: MacOS",
    "Operating System :: Unix"
]
keywords = ["ase", "surface", "atoms", "molecule", "chemistry", "adsorbate", "random forest", "classification"]
dependencies = [
    "numpy",
    "scipy",
    "scikit-learn",
    "dscribe",
    "ase",
    "matplotlib"
]
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/joegilkes/ASESurfaceFinder"